CREATE DATABASE GameCollection;

USE GameCollection;

CREATE TABLE Games (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    GameID UUID UNIQUE DEFAULT (UUID()),
    Title VARCHAR(255) NOT NULL,
    ReleaseYear YEAR,
    Developer VARCHAR(255)
);

CREATE TABLE Genres (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    GenreID UUID UNIQUE DEFAULT (UUID()),
    Name VARCHAR(100) NOT NULL
);

CREATE TABLE Platforms (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PlatformID UUID UNIQUE DEFAULT (UUID()),
    Name VARCHAR(100) NOT NULL
);

CREATE TABLE Games_Genres (
    GameGenreID INT AUTO_INCREMENT PRIMARY KEY,
    GameID UUID,
    GenreID UUID,
    FOREIGN KEY (GameID) REFERENCES Games(GameID),
    FOREIGN KEY (GenreID) REFERENCES Genres(GenreID)
);

CREATE TABLE Games_Platforms (
    GamePlatformID INT AUTO_INCREMENT PRIMARY KEY,
    GameID UUID,
    PlatformID UUID,
    FOREIGN KEY (GameID) REFERENCES Games(GameID),
    FOREIGN KEY (PlatformID) REFERENCES Platforms(PlatformID)
);

CREATE TABLE Users (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    UserID UUID UNIQUE DEFAULT (UUID()),
    Username VARCHAR(255) UNIQUE NOT NULL,
    Email VARCHAR(255) UNIQUE NOT NULL,
    Password VARCHAR(255) NOT NULL
);

CREATE TABLE UserGameList (
    UserGameListID INT AUTO_INCREMENT PRIMARY KEY,
    UserID UUID,
    GameID UUID,
    Status VARCHAR(100),
    FOREIGN KEY (UserID) REFERENCES Users(UserID),
    FOREIGN KEY (GameID) REFERENCES Games(GameID)
);
